{
    "name":"JustSwap Default List",
    "tokens":[
        {
            "symbol":"SUN",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":18,
            "name":"SUN TOKEN",
            "logoURI":"https://coin.top/production/logo/SUNLogo.178d4636.png"
        },
        {
            "symbol":"BTC",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":8,
            "name":"Bitcoin",
            "logoURI":"https://coin.top/production/logo/TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9.png"
        },
        {
            "symbol":"WBTC",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":8,
            "name":"Wrapped BTC",
            "logoURI":"https://coin.top/production/logo/TXpw8XeWYeTUd4quDskoUqeQPowRh4jY65.png"
        },
        {
            "symbol":"ETH",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":18,
            "name":"Ethereum",
            "logoURI":"https://coin.top/production/logo/THb4CqiFdwNHsWsQCs4JhzwjMWys4aqCbF.png"
        },
        {
            "symbol":"WETH",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":18,
            "name":"Wrapped ETH",
            "logoURI":"https://coin.top/production/logo/TXWkP3jLBqRGojUih1ShzNyDaN5Csnebok.png"
        },
        {
            "symbol":"WBTT",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped BitTorrent",
            "logoURI":"https://coin.top/production/logo/TKfjV9RNKJJCqPvBtK8L7Knykh7DNWvnYt.png"
        },
        {
            "symbol":"WTRX",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped TRX",
            "logoURI":"https://coin.top/production/upload/logo/TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR.png"
        },
        {
            "symbol":"JST",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":18,
            "name":"JUST GOV v1.0",
            "logoURI":"https://coin.top/production/logo/just_icon.png"
        },
        {
            "symbol":"WIN",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":6,
            "name":"WINK",
            "logoURI":"https://coin.top/profile_images/JKtJTydD_400x400.jpg"
        },
        {
            "symbol":"DICE",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":6,
            "name":"TRONbetDice",
            "logoURI":"https://coin.top/production/logo/TKttnV3FSY1iEoAwB4N52WK2DxdV94KpSd.jpg"
        },
        {
            "symbol":"LIVE",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1,
            "decimals":6,
            "name":"TRONbetLive",
            "logoURI":"https://coin.top/production/upload/logo/TVgAYofpQku5G4zenXnvxhbZxpzzrk8WVK.png"
        },
        {
            "symbol":"USDT",
            "address":"THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1",
            "decimals":6",
            "name":"Tether USD",
            "logoURI":https://coin.top/production/logo/usdtlogo.png"
        },
        {
            "symbol":USDJ",
            "address":THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1",
            "decimals":18",
            "name":JUST Stablecoin v1.1",
            "logoURI":https://coin.top/production/logo/usdj.png"
        },
        {
            "symbol":LTC",
            "address":THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC", 
            "chainId":1",
            "decimals":8",
            "name":Litecoin",
            "logoURI":https://coin.top/production/logo/TR3DLthpnDdCGabhVDbD3VMsiJoCXY3bZd.png"
        },
        {
            "symbol":HT",
            "address":THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC",
            "chainId":1",
            "decimals":18",
            "name":HuobiToken",
            "logoURI":https://coin.top/production/logo/THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC.png"
        }
    ],
    "logoURI":HTTPS://justswap.io/favicon.ico",
    "version":{
        "patch":1,
        "major":1,
        "minor":0
    },
    "timestamp":1611147166000
}
